version: "3.9"

services:
  db:
    image: "postgres"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "todo"
  server:
    build: .
    ports:
      - "3005:3005"
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/todo?schema=public"